apiVersion: v1
kind: Service
metadata:
  name: next-second-app-service
  labels:
    app: next-second-app
spec:
  type: LoadBalancer
  selector:
    app: next-second-app
  ports:
    - port: 3000
      targetPort: 3000
