name: Clean Up Specific Services

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  cleanup_services:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 2: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 3: Get AKS Credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

    # Step 4: Delete Specific Services
    - name: Delete Specific Services
      run: |
        echo "Deleting specific services..."
        kubectl delete service gita-nextjs-app

    # Step 5: Verify Cleanup
    - name: Verify Cleanup
      run: |
        echo "Listing remaining deployments and services..."
        kubectl get deployments
        kubectl get services
